services:
  mongodb:
    image: mongo:latest
    container_name: trabalho_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: trabalho_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: